version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Meesum3595/invoice
    docker:
      - image: circleci/golang:1.8
    environment:
      GO15VENDOREXPERIMENT: 1
    branches:
      only:
        - main  # Updated from 'master' to 'main'
    steps:
      - checkout
      - setup_remote_docker

      # Set up environment variables
      - run: echo 'export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"' >> $BASH_ENV
      - run: echo 'export GOPATH_BASE="${GOPATH_HEAD}/src/github.com/${CIRCLE_PROJECT_USERNAME}"' >> $BASH_ENV
      - run: mkdir -p "${GOPATH_BASE}"
      - run: mkdir -p "${GOPATH_HEAD}/bin"
      - run: go get github.com/govend/govend

      # Build the application
      - run:
          name: Build application binary
          command: |
            go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
            [ ! -e bin ] && mkdir bin;
            cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;

      # Run the application in the background for testing
      - run:
          name: Run application in background
          command: |
            ./bin/invoicer &
          background: true

      # Test dependencies are up to date
      - run:
          name: Test dependencies are up to date
          command: 'GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u --prune && git diff --quiet )'

      # Deploy to local machine
      - deploy:
          name: Deploy to local machine
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then  # Updated from 'master' to 'main'
              echo "Copying application to local machine..."
              scp -r bin/invoicer user@your_local_ip:/path/to/deploy
              ssh user@your_local_ip "cd /path/to/deploy && ./invoicer"
            fi
