version: 2.1  # Updated to use CircleCI 2.1 syntax

jobs:
  build:
    working_directory: /go/src/github.com/Meesum3595/invoice
    docker:
      - image: golang:1.23  # Ensure Go version is 1.23+ to support dependencies
    environment:
      GO15VENDOREXPERIMENT: 1
    steps:
      - checkout
      - setup_remote_docker

      # Ensure correct working directory
      - run:
          name: Check if go.mod exists
          command: |
            ls -l /go/src/github.com/Meesum3595/invoice

      # Initialize Go module if missing
      - run:
          name: Initialize Go module
          command: |
            cd /go/src/github.com/Meesum3595/invoice
            if [ ! -f go.mod ]; then
              go mod init github.com/Meesum3595/invoice
            fi
            go mod tidy
            go mod vendor

      # Install dependencies
      - run:
          name: Install dependencies
          command: go mod download

      # Build the application
      - run:
          name: Build application binary
          command: |
            cd /go/src/github.com/Meesum3595/invoice
            go build -mod=vendor -o bin/invoicer .

      # Run the application in the background for testing
      - run:
          name: Run application in background
          command: |
            ./bin/invoicer &
          background: true

      # Deploy the application if branch is "main"
      - deploy:
          name: Deploy to server
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "Deploying to server..."
              scp -r bin/invoicer kali@0.tcp.ap.ngrok.io -P 17247:/home/kali/invoicer-chapter3
              ssh kali@0.tcp.ap.ngrok.io -p 17247 "cd /home/kali/invoicer-chapter3 && ./invoicer"
            fi
