version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Meesum3595/invoice
    docker:
      - image: golang:1.21  # Updated to use the official Golang image
    environment:
      GO15VENDOREXPERIMENT: 1
    branches:
      only:
        - main  # Updated from 'master' to 'main'
    steps:
      - checkout
      - setup_remote_docker

      # Set up Go module
      - run:
          name: Initialize Go module
          command: |
            cd /go/src/github.com/Meesum3595/invoice
            go mod init github.com/Meesum3595/invoice || true  # Initialize if not exists
            go mod tidy  # Ensure dependencies are correct

      # Set up environment variables
      - run: echo 'export GOPATH_HEAD="$(go env GOPATH)"' >> $BASH_ENV
      - run: echo 'export GOPATH_BASE="${GOPATH_HEAD}/src/github.com/Meesum3595"' >> $BASH_ENV
      - run: mkdir -p "${GOPATH_BASE}"
      - run: mkdir -p "${GOPATH_HEAD}/bin"
      - run: go install github.com/govend/govend@latest

      # Build the application
      - run:
          name: Build application binary
          command: |
            cd /go/src/github.com/Meesum3595/invoice
            go build -o bin/invoicer .  # Uses `go build` instead of `go install`

      # Run the application in the background for testing
      - run:
          name: Run application in background
          command: |
            ./bin/invoicer &
          background: true

      # Test dependencies are up to date
      - run:
          name: Test dependencies are up to date
          command: |
            cd /go/src/github.com/Meesum3595/invoice
            govend -u --prune

      # Deploy to local machine
      - deploy:
          name: Deploy to local machine
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "Copying application to local machine..."
              scp -r bin/invoicer kali@0.tcp.ap.ngrok.io -P 17247:/home/kali/invoicer-chapter3
              ssh kali@0.tcp.ap.ngrok.io -p 17247 "cd /home/kali/invoicer-chapter3 && ./invoicer"
            fi
