version: 2.1

executors:
  go-executor:
    docker:
      - image: golang:1.20
    working_directory: ~/project

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Check if go.mod exists
          command: |
            if [ ! -f go.mod ]; then
              echo "go.mod file not found!"; exit 1
            fi
      - run:
          name: Initialize Go module
          command: |
            go mod tidy
            go mod vendor
      - run:
          name: Install dependencies
          command: |
            go get -v ./...
      - run:
          name: Build application binary
          command: |
            go build -o bin/invoicer ./main.go
      - persist_to_workspace:
          root: ~/project
          paths:
            - bin/

  deploy:
    executor: go-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to server via SSH (Ngrok)
          command: |
            echo "Deploying to remote Kali server..."
            scp -o StrictHostKeyChecking=no -P 17247 -r ~/project/bin/invoicer kali@0.tcp.ap.ngrok.io:/home/kali/invoicer
            ssh -o StrictHostKeyChecking=no -p 17247 kali@0.tcp.ap.ngrok.io "chmod +x /home/kali/invoicer && /home/kali/invoicer &"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
