version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Meesum3595/invoice  # Updated to your repo
    docker:
      - image: circleci/golang:1.8
    environment:
      GO15VENDOREXPERIMENT: 1
    branches:
      only:
        - main  # Updated from 'master' to 'main'
    steps:
      - checkout
      - setup_remote_docker

      # Set up environment variables
      - run: echo 'export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"' >> $BASH_ENV
      - run: echo 'export GOPATH_BASE="${GOPATH_HEAD}/src/github.com/Meesum3595"' >> $BASH_ENV  # Updated to your GitHub username
      - run: mkdir -p "${GOPATH_BASE}"
      - run: mkdir -p "${GOPATH_HEAD}/bin"
      - run: go get github.com/govend/govend

      # Build the application
      - run:
          name: Build application binary
          command: |
            go install --ldflags '-extldflags "-static"' github.com/Meesum3595/invoice;  # Updated to your repo
            [ ! -e bin ] && mkdir bin;
            cp "${GOPATH_HEAD}/bin/invoice" bin/invoicer;  # Updated binary name

      # Run the application in the background for testing
      - run:
          name: Run application in background
          command: |
            ./bin/invoicer &
          background: true

      # Test dependencies are up to date
      - run:
          name: Test dependencies are up to date
          command: 'GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/invoice && govend -u --prune )'  # Removed git diff --quiet

      # Deploy to local machine
      - deploy:
          name: Deploy to local machine
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then  # Updated from 'master' to 'main'
              echo "Copying application to local machine..."
              scp -r bin/invoicer kali@192.168.1.10:/home/kali/invoicer-chapter3
              ssh kali@192.168.1.10 "cd /home/kali/invoicer-chapter3 && ./invoicer"
            fi
